apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-d
  labels:
    app: postgres-d
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: common-name-voting
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: common-name-voting
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
