apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-d
  labels:
    app: redis-d
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: common-name-voting
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: common-name-voting
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
