apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-d
  labels:
    app: result-d
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-pod
      app: common-name-voting
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
        app: common-name-voting
    spec:
      containers:
        - name: result-container
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
